# Find nullspace matrix N from Rx=0
任意の行列Aのnull space matrix Nを計算します。最初は教科書どおりrrefを用いた例を示します。<br>
公式のMATLABコードは[こちら](http://web.mit.edu/18.06/www/Course-Info/Mfiles/nulbasis.m)です。


In [5]:
import numpy as np
# numpy,scipyにはrrefを計算する関数はありません。
# sympyはsymbolic computationのためのパッケージでnumpyとはかなり性質が異なりますが、pythonでrrefを計算するモジュールはこれしかないのでこれを使います。
from sympy import Matrix

In [6]:
A = np.matrix([[1, 2, 0, 3],[0, 0, 1, 4]])
A

matrix([[1, 2, 0, 3],
        [0, 0, 1, 4]])

In [7]:
def nullbasis(A):
    # sympyのrref関数はrref行列Rとpivot columnsのindexを返します
    R, pivot_col = Matrix(A).rref()
    R = np.matrix(R).astype(np.float64)
    # ランク＝pivotの数; free columnsの数の決定に必要
    r = len(pivot_col)
    [m,n] = A.shape
    # Null matrix のサイズ＝（columnsの数,free columnsの数）
    N = np.zeros((n, n-r))
    # free columnsのindex = すべてのカラムのindexからpicot columnsのindexを除外したもの
    free_col = np.delete(np.arange(n), pivot_col)
    # free columnsの場所にIを代入
    N[free_col] = np.eye(n-r)
    # pivot columnsの場所には-Rを代入
    N[[pivot_col]] = -R[:r, free_col]
    return N

In [8]:
nullbasis(A)

array([[-2., -3.],
       [ 1.,  0.],
       [-0., -4.],
       [ 0.,  1.]])

In [9]:
A = np.matrix([[1,3,2],[2,6,4],[2,8,6],[2,10,8]])
A

matrix([[ 1,  3,  2],
        [ 2,  6,  4],
        [ 2,  8,  6],
        [ 2, 10,  8]])

In [10]:
nullbasis(A)

array([[ 1.],
       [-1.],
       [ 1.]])

# Find Nullspace matrix N with SVD
numpy,scipyにrrefの実装がないことからも分かるとおり、計算機においてはrrefを使って何かを計算することはほぼないそうです。
理由は、[大手掲示板](http://numpy-discussion.10968.n7.nabble.com/Reduced-row-echelon-form-td16486.html)によると「rrefはその数が0なのか0に近い小さな数なのかの判断が何回も必要になるので、浮動小数点を使う計算機では完全に使い物にならない」からだそうです。その点て言うと、sympyは数値的な計算ではなく記号の計算をしているのでrrefの計算ができるということなのでしょうか。

ともかく、せっかくなので計算機の世界において実用的な方法も少し試してみたいと思います。一番ポピュラーなのはSVDを用いた解法らしいのでSVDを使った解法を試してみます。

In [11]:
# -----SVDによる実装（第7章で加筆予定）